"""Pin: every user-facing pitch / regulator / judge document MUST NOT
cite pre-v8 weight or size fossils outside an explicit historical /
v1-baseline / audit-chain-reconstruction context.

Iter-306 T1 round-64 (27th cross-pin family). Broader companion to the
iter-301 demo.html-only cross-pin: where iter-301 catches stale `43/43`
+ `42 contra` fossils inside three demo.html-specific phrases (aggregate
+ promotion + cohort-breakdown), iter-306 catches the **weight-count and
bundle-size fossils** (8,517 / 8,581 / 19 KB) across **all** user-facing
markdown + HTML surfaces.

Caught at iter-303 audit (4 stale v1-era refs in DEVPOST/script/FDA-draft
that iter-301's demo.html pin did NOT cover):

  • DEVPOST.md L87           '8,517 ternary weights / 19 KB' (current tense)
  • DEVPOST.md L88           '35/35 contra + 31/35 major' (current tense)
  • demo-script-v2.md L82    Pitch badges still cited 8,517 / 19 KB
  • fda_q_sub_draft.md §5.1  v1 architecture as the LIVE primitive

iter-303 fixed those four surfaces in prose; iter-306 (this pin) prevents
the class from regressing on the same docs AND catches new files that
inherit the same drift.

Surfaces scanned
================
  • DEVPOST.md
  • demo-script-v2.md
  • README.md
  • JUDGES.md
  • docs/fda_q_sub_draft.md
  • docs/edge_pi_offline.md
  • docs/bitnet_training.md
  • docs/why_bitnet_b158.md
  • docs/demo.html

Allowlist tokens (line OR adjacent line — covers 8,517 / 8,581 / 19 KB
references that ARE legitimate historical / audit-chain-reconstruction
prose and SHOULD remain on disk for FDA SaMD decade-replay rigor):

  - pre-promotion
  - v1 baseline
  - pre-v8
  - preserved at
  - preserved on disk
  - cfadb4f6
  - audit-chain reconstruction
  - audit-trail rigor
  - historical anchor
  - historical bundle
  - decade-replay
  - prior bundle
  - bdaf385a       (iter-26 historical anchor)

Files NOT scanned (intentionally excluded):
  - AGENTS.md                    — auto-regenerated by claude-mem
  - AUTONOMOUS_WORK_LOG.md       — append-only iteration log
  - .mind_mem_watch_state.json   — append-only state
  - docs/eval_runs/*             — frozen eval artifacts
  - tests/*                      — pin assertions (legitimately
                                    reference v1 baseline numbers)
  - retrain_runpod/*             — training scripts (v1-era trainer
                                    comments are part of the lineage)
  - CONSENSUS_*.json             — frozen multi-LLM eval snapshots
"""
from __future__ import annotations

import re
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent
_USER_FACING_DOCS = (
    _REPO_ROOT / "DEVPOST.md",
    _REPO_ROOT / "demo-script-v2.md",
    _REPO_ROOT / "README.md",
    _REPO_ROOT / "JUDGES.md",
    _REPO_ROOT / "docs" / "fda_q_sub_draft.md",
    _REPO_ROOT / "docs" / "edge_pi_offline.md",
    _REPO_ROOT / "docs" / "bitnet_training.md",
    _REPO_ROOT / "docs" / "why_bitnet_b158.md",
    _REPO_ROOT / "docs" / "demo.html",
    # iter-316 scope extension: clinical_validation.md was missed by the
    # iter-306 sweep but iter-308 caught 5 stale v1-era refs in it
    # (35/35, 31/35, 85.7%, n=42, etc.). Add to scope so the same
    # fossil class can never regress here.
    _REPO_ROOT / "docs" / "clinical_validation.md",
)

# Historical-context tokens — ANY of these on the same line OR an
# adjacent line legitimises a v1-fossil mention. Match case-insensitive.
_HISTORICAL_TOKENS = (
    "pre-promotion",
    "v1 baseline",
    "pre-v8",
    "preserved at",
    "preserved on disk",
    "cfadb4f6",
    "audit-chain reconstruction",
    "audit-trail rigor",
    "historical anchor",
    "historical bundle",
    "decade-replay",
    "prior bundle",
    "bdaf385a",
    "v1 backup",
)


def _line_window_ok(lines: list[str], idx: int) -> bool:
    """A v1 fossil at lines[idx] is OK iff a historical token appears
    in the same line OR on either adjacent line (3-line window).

    The 3-line window absorbs HTML/markdown line-wrapping where the
    fossil and its 'preserved at...' contextualizing phrase end up on
    different physical lines.
    """
    lo = max(0, idx - 1)
    hi = min(len(lines), idx + 2)
    window = " ".join(lines[lo:hi]).lower()
    return any(tok in window for tok in _HISTORICAL_TOKENS)


def test_no_8517_in_current_tense_user_facing_docs():
    """The number 8,517 (the historical incorrect ternary-count
    approximation that pre-iter-100 docs used to cite for the v1
    baseline) must not appear in any user-facing doc outside an
    explicit historical context. v1 baseline's actual count is 8,512
    ternary + 69 biases = 8,581 params, but the legacy 8,517 form
    occasionally crept in via copy-paste."""
    violations = []
    pat = re.compile(r"\b8,?517\b")
    for doc in _USER_FACING_DOCS:
        if not doc.exists():
            continue
        lines = doc.read_text().splitlines()
        for i, line in enumerate(lines):
            if pat.search(line) and not _line_window_ok(lines, i):
                violations.append(
                    f"{doc.relative_to(_REPO_ROOT)}:{i+1}: {line.strip()[:140]!r}"
                )
    assert not violations, (
        "Pre-v8 ternary-count fossil '8,517' / '8517' appears in "
        "user-facing docs outside an explicit historical / v1-baseline "
        "/ audit-chain-reconstruction context. Either rephrase to v8 "
        "(50,688 ternary weights / 50,949 params / ~118 KB / bundle "
        "1f0f8859…) or surround with a historical token. Hits:\n"
        + "\n".join(f"  - {v}" for v in violations[:10])
    )


def test_no_8581_in_current_tense_user_facing_docs():
    """The 8,581 v1-baseline param count is fine in historical /
    audit-chain context but not as a current-tense claim about the
    LIVE engine (which is v8 with 50,949 params)."""
    violations = []
    pat = re.compile(r"\b8,?581\b")
    for doc in _USER_FACING_DOCS:
        if not doc.exists():
            continue
        lines = doc.read_text().splitlines()
        for i, line in enumerate(lines):
            if pat.search(line) and not _line_window_ok(lines, i):
                violations.append(
                    f"{doc.relative_to(_REPO_ROOT)}:{i+1}: {line.strip()[:140]!r}"
                )
    assert not violations, (
        "v1-baseline param count '8,581' / '8581' appears in user-"
        "facing docs outside an explicit historical / v1-baseline "
        "context. The live engine (v8, iter-275 promotion) has 50,949 "
        "params (50,688 ternary + 261 Q16.16 biases / ~118 KB / bundle "
        "1f0f8859…). v1 references are legitimate ONLY in audit-chain "
        "reconstruction prose. Hits:\n"
        + "\n".join(f"  - {v}" for v in violations[:10])
    )


def test_no_19kb_engine_claim_in_current_tense():
    """The 19 KB v1-baseline JSON serialisation size must not appear
    as a current-tense claim about the LIVE engine bundle (which is
    ~118 KB at v8). Allowed only in v1-baseline / audit-chain context."""
    violations = []
    # Match "19 KB" / "19KB" / "19 kB" / "19&nbsp;KB" etc. but NOT a
    # number like "1190 KB" or "190 KB" or coordinates like "y=19".
    # Anchor on word boundary + KB/kB unit.
    pat = re.compile(r"\b19\s?(?:&nbsp;)?\s?KB\b", re.IGNORECASE)
    for doc in _USER_FACING_DOCS:
        if not doc.exists():
            continue
        lines = doc.read_text().splitlines()
        for i, line in enumerate(lines):
            if pat.search(line) and not _line_window_ok(lines, i):
                violations.append(
                    f"{doc.relative_to(_REPO_ROOT)}:{i+1}: {line.strip()[:140]!r}"
                )
    assert not violations, (
        "v1-baseline JSON-serialisation size '19 KB' appears in user-"
        "facing docs outside an explicit historical / v1-baseline "
        "context. The live engine bundle (v8) is ~118 KB. v1 size "
        "references are legitimate ONLY in audit-chain reconstruction "
        "prose. Hits:\n"
        + "\n".join(f"  - {v}" for v in violations[:10])
    )


def test_no_v1_baseline_held_out_metrics_in_current_tense():
    """v1-baseline held-out evaluation metrics — the 85.7% per-class
    contra accuracy on n=42, the 35 / 35 NTI-cohort recall, the
    31 / 35 major-cohort recall — must NOT appear as current-tense
    LIVE-engine claims outside an explicit historical / v1-baseline /
    pre-promotion / held-out / training-fold context.

    iter-316 ratchet (closes the iter-308/iter-313 fossil class that
    the original iter-306 pin didn't pattern-match). iter-308 caught
    5 deeper stale v1-era refs in clinical_validation.md L80-89/L102
    + bitnet_training.md L37/L148/L154 + DEVPOST.md L13 + demo.html
    L1154/L1160 (held-out 85.7% / n=42 / NTI 35/35 cohort). iter-313
    caught the FDA Q-Sub §2.5 narrative gap. All fixed in prose;
    iter-316 (this pin) prevents regression at the fossil-pattern
    layer.

    Allowlist (3-line window from `_HISTORICAL_TOKENS` + held-out /
    training-fold / per-class held-out evaluation tokens that signal
    legitimate v1 baseline citation):
      pre-promotion, v1 baseline, pre-v8, preserved at, cfadb4f6,
      audit-chain reconstruction, audit-trail rigor, historical
      anchor, decade-replay, prior bundle, bdaf385a, v1 backup,
      held-out, held out, training fold, training-time, baseline
      held-out, training-time accuracy, pre-iter-275

    Forbidden patterns (current-tense LIVE-engine claims):
      85.7%   — v1 held-out per-class contra accuracy
      35/35   — v1 NTI-cohort full-recall claim
      31/35   — v1 major-cohort recall claim
      n=42    — v1 held-out contra test set size
    """
    # Extended allowlist — held-out / training-fold tokens are
    # ALSO legitimate historical context for these fossils.
    extended_tokens = _HISTORICAL_TOKENS + (
        "held-out",
        "held out",
        "training fold",
        "training-time",
        "training-time accuracy",
        "pre-iter-275",
    )

    def _ext_line_window_ok(lines: list[str], idx: int) -> bool:
        # Standard 3-line window
        lo = max(0, idx - 1)
        hi = min(len(lines), idx + 2)
        window = " ".join(lines[lo:hi]).lower()
        if any(tok in window for tok in extended_tokens):
            return True
        # Section-level fallback: scan upward from idx for the nearest
        # markdown / HTML heading line and check whether IT carries a
        # historical token. Tables and code blocks under a `### Pre-
        # promotion v1 baseline` heading are legitimately historical.
        # Stop at any `## ` or `### ` line, or after 50 lines back.
        for j in range(idx - 1, max(0, idx - 50) - 1, -1):
            line_lower = lines[j].lower()
            if line_lower.lstrip().startswith(("## ", "### ", "#### ",
                                                "<h2", "<h3", "<h4")):
                if any(tok in line_lower for tok in extended_tokens):
                    return True
                # Hit a heading WITHOUT a token — stop scanning; we're
                # in a different section.
                return False
        return False

    forbidden_patterns = (
        (re.compile(r"\b85\.7\s*%"), "85.7%"),
        (re.compile(r"\b35\s*/\s*35\b"), "35/35"),
        (re.compile(r"\b31\s*/\s*35\b"), "31/35"),
        (re.compile(r"\bn\s*=\s*42\b"), "n=42"),
    )
    violations = []
    for doc in _USER_FACING_DOCS:
        if not doc.exists():
            continue
        lines = doc.read_text().splitlines()
        for i, line in enumerate(lines):
            for pat, label in forbidden_patterns:
                if pat.search(line) and not _ext_line_window_ok(lines, i):
                    violations.append(
                        f"{doc.relative_to(_REPO_ROOT)}:{i+1} [{label}]: "
                        f"{line.strip()[:140]!r}"
                    )
    assert not violations, (
        "v1-baseline held-out evaluation metrics appear as current-tense "
        "LIVE-engine claims in user-facing docs. Either reframe to lead "
        "with v8 LIVE numbers (44/44 + 4/4 major + 0 FP under Q16.16 on "
        "the 139-pair PCCP cohort) or wrap with a historical / v1 "
        "baseline / held-out token. Hits:\n"
        + "\n".join(f"  - {v}" for v in violations[:10])
    )


def test_at_least_one_doc_actually_cites_v8_live_bundle():
    """Sanity gate — at least ONE of the user-facing docs MUST cite
    the live v8 bundle id `1f0f8859`. Catches the scenario where a
    future maintainer accidentally rolls back to a v1-only narrative
    across all surfaces (would otherwise produce zero violations
    above but also zero v8 mentions)."""
    cited = []
    pat = re.compile(r"\b1f0f8859\b")
    for doc in _USER_FACING_DOCS:
        if not doc.exists():
            continue
        if pat.search(doc.read_text()):
            cited.append(doc.relative_to(_REPO_ROOT))
    assert cited, (
        "No user-facing doc cites the live v8 bundle id '1f0f8859'. "
        "Either the v8 promotion was rolled back (which would require "
        "deliberate cascade work — see the iter-275 promotion log) or "
        "all user-facing surfaces lost the live bundle reference at "
        "the same time. Both warrant inspection."
    )
